deploy_user: edox-cicd-s
deploy_group: root
devops_compose_files_dir: /opt/docker
docker_logging_driver: syslog
docker_logging_tag:  "{%raw%}docker/{{.Name}}/{{.Name}}{%endraw%}"
docker_logging_dir: "/var/log/docker"
docker_syslog_address: udp://127.0.0.1:10514
env_code: uat
env_docker: staging
consul_env_code: pp-edou01
consul_env_path: pp/edou01
docker_network_name: edox
dotnet_environment: "Staging"
edox_auto_service_grpc_common_name: https://uat-edox-auto.firm.ru
service_grpc_common_name: https://uat-edox-grpc.firm.ru
vault_agent_api_url: "http://127.0.0.1:8102"
vault_agent_name_directory: "vault_proxy_uat_edox_web"
vault_ansible_secret_path: "project/data/edox_web/{{ env_code }}/ansible_secrets"
