deploy_user: edox-cicd-s
deploy_group: root
devops_compose_files_dir: /opt/docker
env_code: uat
env_docker: staging
consul_env_code: pp-edou01
consul_env_path: pp/edou01
docker_network_name: edox-web
dotnet_environment: "Staging"
vault_agent_api_url: "http://127.0.0.1:8102"
vault_agent_name_directory: "vault_proxy_uat_edox_web"
vault_ansible_secret_path: "project/data/edox_web/{{ env_code }}/ansible_secrets"
